package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class Advertising {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long advertisingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String advertisingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_manufacturer
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String advertisingManufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_location
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String advertisingLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_cost
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String advertisingCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date advertisingCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_start_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date advertisingStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_end_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date advertisingEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.advertising_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String advertisingState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_id
     *
     * @return the value of advertising.advertising_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getAdvertisingId() {
        return advertisingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_id
     *
     * @param advertisingId the value for advertising.advertising_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingId(Long advertisingId) {
        this.advertisingId = advertisingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_name
     *
     * @return the value of advertising.advertising_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAdvertisingName() {
        return advertisingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_name
     *
     * @param advertisingName the value for advertising.advertising_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingName(String advertisingName) {
        this.advertisingName = advertisingName == null ? null : advertisingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_manufacturer
     *
     * @return the value of advertising.advertising_manufacturer
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAdvertisingManufacturer() {
        return advertisingManufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_manufacturer
     *
     * @param advertisingManufacturer the value for advertising.advertising_manufacturer
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingManufacturer(String advertisingManufacturer) {
        this.advertisingManufacturer = advertisingManufacturer == null ? null : advertisingManufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_location
     *
     * @return the value of advertising.advertising_location
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAdvertisingLocation() {
        return advertisingLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_location
     *
     * @param advertisingLocation the value for advertising.advertising_location
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingLocation(String advertisingLocation) {
        this.advertisingLocation = advertisingLocation == null ? null : advertisingLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_cost
     *
     * @return the value of advertising.advertising_cost
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAdvertisingCost() {
        return advertisingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_cost
     *
     * @param advertisingCost the value for advertising.advertising_cost
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingCost(String advertisingCost) {
        this.advertisingCost = advertisingCost == null ? null : advertisingCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_create_time
     *
     * @return the value of advertising.advertising_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getAdvertisingCreateTime() {
        return advertisingCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_create_time
     *
     * @param advertisingCreateTime the value for advertising.advertising_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingCreateTime(Date advertisingCreateTime) {
        this.advertisingCreateTime = advertisingCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_start_time
     *
     * @return the value of advertising.advertising_start_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getAdvertisingStartTime() {
        return advertisingStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_start_time
     *
     * @param advertisingStartTime the value for advertising.advertising_start_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingStartTime(Date advertisingStartTime) {
        this.advertisingStartTime = advertisingStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_end_time
     *
     * @return the value of advertising.advertising_end_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getAdvertisingEndTime() {
        return advertisingEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_end_time
     *
     * @param advertisingEndTime the value for advertising.advertising_end_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingEndTime(Date advertisingEndTime) {
        this.advertisingEndTime = advertisingEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.advertising_state
     *
     * @return the value of advertising.advertising_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAdvertisingState() {
        return advertisingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.advertising_state
     *
     * @param advertisingState the value for advertising.advertising_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAdvertisingState(String advertisingState) {
        this.advertisingState = advertisingState == null ? null : advertisingState.trim();
    }
}