package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class Banner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long bannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_url
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_image_url
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_sort
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_type
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_desc
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String bannerDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.banner_cteate_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date bannerCteateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_id
     *
     * @return the value of banner.banner_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_id
     *
     * @param bannerId the value for banner.banner_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerId(Long bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_name
     *
     * @return the value of banner.banner_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerName() {
        return bannerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_name
     *
     * @param bannerName the value for banner.banner_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerName(String bannerName) {
        this.bannerName = bannerName == null ? null : bannerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_url
     *
     * @return the value of banner.banner_url
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_url
     *
     * @param bannerUrl the value for banner.banner_url
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl == null ? null : bannerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_image_url
     *
     * @return the value of banner.banner_image_url
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerImageUrl() {
        return bannerImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_image_url
     *
     * @param bannerImageUrl the value for banner.banner_image_url
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerImageUrl(String bannerImageUrl) {
        this.bannerImageUrl = bannerImageUrl == null ? null : bannerImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_sort
     *
     * @return the value of banner.banner_sort
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerSort() {
        return bannerSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_sort
     *
     * @param bannerSort the value for banner.banner_sort
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerSort(String bannerSort) {
        this.bannerSort = bannerSort == null ? null : bannerSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_type
     *
     * @return the value of banner.banner_type
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerType() {
        return bannerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_type
     *
     * @param bannerType the value for banner.banner_type
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerType(String bannerType) {
        this.bannerType = bannerType == null ? null : bannerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_state
     *
     * @return the value of banner.banner_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerState() {
        return bannerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_state
     *
     * @param bannerState the value for banner.banner_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerState(String bannerState) {
        this.bannerState = bannerState == null ? null : bannerState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_desc
     *
     * @return the value of banner.banner_desc
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getBannerDesc() {
        return bannerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_desc
     *
     * @param bannerDesc the value for banner.banner_desc
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerDesc(String bannerDesc) {
        this.bannerDesc = bannerDesc == null ? null : bannerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.banner_cteate_time
     *
     * @return the value of banner.banner_cteate_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getBannerCteateTime() {
        return bannerCteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.banner_cteate_time
     *
     * @param bannerCteateTime the value for banner.banner_cteate_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setBannerCteateTime(Date bannerCteateTime) {
        this.bannerCteateTime = bannerCteateTime;
    }
}