package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_province_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long cityProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String cityState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date cityCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_province_id
     *
     * @return the value of city.city_province_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getCityProvinceId() {
        return cityProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_province_id
     *
     * @param cityProvinceId the value for city.city_province_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setCityProvinceId(Long cityProvinceId) {
        this.cityProvinceId = cityProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_state
     *
     * @return the value of city.city_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getCityState() {
        return cityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_state
     *
     * @param cityState the value for city.city_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setCityState(String cityState) {
        this.cityState = cityState == null ? null : cityState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_create_time
     *
     * @return the value of city.city_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getCityCreateTime() {
        return cityCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_create_time
     *
     * @param cityCreateTime the value for city.city_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setCityCreateTime(Date cityCreateTime) {
        this.cityCreateTime = cityCreateTime;
    }
}