package com.rivis.feng.website.pojo.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CurriculumOrderAlipayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public CurriculumOrderAlipayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderAlipayIdIsNull() {
            addCriterion("order_alipay_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdIsNotNull() {
            addCriterion("order_alipay_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdEqualTo(Long value) {
            addCriterion("order_alipay_id =", value, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdNotEqualTo(Long value) {
            addCriterion("order_alipay_id <>", value, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdGreaterThan(Long value) {
            addCriterion("order_alipay_id >", value, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_alipay_id >=", value, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdLessThan(Long value) {
            addCriterion("order_alipay_id <", value, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdLessThanOrEqualTo(Long value) {
            addCriterion("order_alipay_id <=", value, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdIn(List<Long> values) {
            addCriterion("order_alipay_id in", values, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdNotIn(List<Long> values) {
            addCriterion("order_alipay_id not in", values, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdBetween(Long value1, Long value2) {
            addCriterion("order_alipay_id between", value1, value2, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayIdNotBetween(Long value1, Long value2) {
            addCriterion("order_alipay_id not between", value1, value2, "orderAlipayId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdIsNull() {
            addCriterion("curriculum_order_id is null");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdIsNotNull() {
            addCriterion("curriculum_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdEqualTo(Long value) {
            addCriterion("curriculum_order_id =", value, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdNotEqualTo(Long value) {
            addCriterion("curriculum_order_id <>", value, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdGreaterThan(Long value) {
            addCriterion("curriculum_order_id >", value, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("curriculum_order_id >=", value, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdLessThan(Long value) {
            addCriterion("curriculum_order_id <", value, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("curriculum_order_id <=", value, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdIn(List<Long> values) {
            addCriterion("curriculum_order_id in", values, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdNotIn(List<Long> values) {
            addCriterion("curriculum_order_id not in", values, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdBetween(Long value1, Long value2) {
            addCriterion("curriculum_order_id between", value1, value2, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andCurriculumOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("curriculum_order_id not between", value1, value2, "curriculumOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdIsNull() {
            addCriterion("order_alipay_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdIsNotNull() {
            addCriterion("order_alipay_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdEqualTo(Long value) {
            addCriterion("order_alipay_user_id =", value, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdNotEqualTo(Long value) {
            addCriterion("order_alipay_user_id <>", value, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdGreaterThan(Long value) {
            addCriterion("order_alipay_user_id >", value, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_alipay_user_id >=", value, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdLessThan(Long value) {
            addCriterion("order_alipay_user_id <", value, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdLessThanOrEqualTo(Long value) {
            addCriterion("order_alipay_user_id <=", value, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdIn(List<Long> values) {
            addCriterion("order_alipay_user_id in", values, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdNotIn(List<Long> values) {
            addCriterion("order_alipay_user_id not in", values, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdBetween(Long value1, Long value2) {
            addCriterion("order_alipay_user_id between", value1, value2, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayUserIdNotBetween(Long value1, Long value2) {
            addCriterion("order_alipay_user_id not between", value1, value2, "orderAlipayUserId");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateIsNull() {
            addCriterion("order_alipay_state is null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateIsNotNull() {
            addCriterion("order_alipay_state is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateEqualTo(String value) {
            addCriterion("order_alipay_state =", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateNotEqualTo(String value) {
            addCriterion("order_alipay_state <>", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateGreaterThan(String value) {
            addCriterion("order_alipay_state >", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateGreaterThanOrEqualTo(String value) {
            addCriterion("order_alipay_state >=", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateLessThan(String value) {
            addCriterion("order_alipay_state <", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateLessThanOrEqualTo(String value) {
            addCriterion("order_alipay_state <=", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateLike(String value) {
            addCriterion("order_alipay_state like", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateNotLike(String value) {
            addCriterion("order_alipay_state not like", value, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateIn(List<String> values) {
            addCriterion("order_alipay_state in", values, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateNotIn(List<String> values) {
            addCriterion("order_alipay_state not in", values, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateBetween(String value1, String value2) {
            addCriterion("order_alipay_state between", value1, value2, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayStateNotBetween(String value1, String value2) {
            addCriterion("order_alipay_state not between", value1, value2, "orderAlipayState");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeIsNull() {
            addCriterion("order_alipay_create_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeIsNotNull() {
            addCriterion("order_alipay_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeEqualTo(Date value) {
            addCriterion("order_alipay_create_time =", value, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeNotEqualTo(Date value) {
            addCriterion("order_alipay_create_time <>", value, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeGreaterThan(Date value) {
            addCriterion("order_alipay_create_time >", value, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_alipay_create_time >=", value, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeLessThan(Date value) {
            addCriterion("order_alipay_create_time <", value, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_alipay_create_time <=", value, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeIn(List<Date> values) {
            addCriterion("order_alipay_create_time in", values, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeNotIn(List<Date> values) {
            addCriterion("order_alipay_create_time not in", values, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeBetween(Date value1, Date value2) {
            addCriterion("order_alipay_create_time between", value1, value2, "orderAlipayCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderAlipayCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_alipay_create_time not between", value1, value2, "orderAlipayCreateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated do_not_delete_during_merge Sat May 19 23:25:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}