package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class CurriculumAppraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long appraiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long appraiseUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_curriculum_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long appraiseCurriculumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_content
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String appraiseContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_is_show
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String appraiseIsShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_agree_number
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String appraiseAgreeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_no_agree_number
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String appraiseNoAgreeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_appraise.appraise_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date appraiseCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_id
     *
     * @return the value of curriculum_appraise.appraise_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getAppraiseId() {
        return appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_id
     *
     * @param appraiseId the value for curriculum_appraise.appraise_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseId(Long appraiseId) {
        this.appraiseId = appraiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_user_id
     *
     * @return the value of curriculum_appraise.appraise_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getAppraiseUserId() {
        return appraiseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_user_id
     *
     * @param appraiseUserId the value for curriculum_appraise.appraise_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseUserId(Long appraiseUserId) {
        this.appraiseUserId = appraiseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_curriculum_id
     *
     * @return the value of curriculum_appraise.appraise_curriculum_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getAppraiseCurriculumId() {
        return appraiseCurriculumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_curriculum_id
     *
     * @param appraiseCurriculumId the value for curriculum_appraise.appraise_curriculum_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseCurriculumId(Long appraiseCurriculumId) {
        this.appraiseCurriculumId = appraiseCurriculumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_content
     *
     * @return the value of curriculum_appraise.appraise_content
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAppraiseContent() {
        return appraiseContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_content
     *
     * @param appraiseContent the value for curriculum_appraise.appraise_content
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseContent(String appraiseContent) {
        this.appraiseContent = appraiseContent == null ? null : appraiseContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_is_show
     *
     * @return the value of curriculum_appraise.appraise_is_show
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAppraiseIsShow() {
        return appraiseIsShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_is_show
     *
     * @param appraiseIsShow the value for curriculum_appraise.appraise_is_show
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseIsShow(String appraiseIsShow) {
        this.appraiseIsShow = appraiseIsShow == null ? null : appraiseIsShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_agree_number
     *
     * @return the value of curriculum_appraise.appraise_agree_number
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAppraiseAgreeNumber() {
        return appraiseAgreeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_agree_number
     *
     * @param appraiseAgreeNumber the value for curriculum_appraise.appraise_agree_number
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseAgreeNumber(String appraiseAgreeNumber) {
        this.appraiseAgreeNumber = appraiseAgreeNumber == null ? null : appraiseAgreeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_no_agree_number
     *
     * @return the value of curriculum_appraise.appraise_no_agree_number
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getAppraiseNoAgreeNumber() {
        return appraiseNoAgreeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_no_agree_number
     *
     * @param appraiseNoAgreeNumber the value for curriculum_appraise.appraise_no_agree_number
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseNoAgreeNumber(String appraiseNoAgreeNumber) {
        this.appraiseNoAgreeNumber = appraiseNoAgreeNumber == null ? null : appraiseNoAgreeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_appraise.appraise_create_time
     *
     * @return the value of curriculum_appraise.appraise_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getAppraiseCreateTime() {
        return appraiseCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_appraise.appraise_create_time
     *
     * @param appraiseCreateTime the value for curriculum_appraise.appraise_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setAppraiseCreateTime(Date appraiseCreateTime) {
        this.appraiseCreateTime = appraiseCreateTime;
    }
}