package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class CurriculumOrderAlipay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_order_alipay.order_alipay_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long orderAlipayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_order_alipay.curriculum_order_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long curriculumOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_order_alipay.order_alipay_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long orderAlipayUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_order_alipay.order_alipay_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String orderAlipayState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculum_order_alipay.order_alipay_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date orderAlipayCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_order_alipay.order_alipay_id
     *
     * @return the value of curriculum_order_alipay.order_alipay_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getOrderAlipayId() {
        return orderAlipayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_order_alipay.order_alipay_id
     *
     * @param orderAlipayId the value for curriculum_order_alipay.order_alipay_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderAlipayId(Long orderAlipayId) {
        this.orderAlipayId = orderAlipayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_order_alipay.curriculum_order_id
     *
     * @return the value of curriculum_order_alipay.curriculum_order_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getCurriculumOrderId() {
        return curriculumOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_order_alipay.curriculum_order_id
     *
     * @param curriculumOrderId the value for curriculum_order_alipay.curriculum_order_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setCurriculumOrderId(Long curriculumOrderId) {
        this.curriculumOrderId = curriculumOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_order_alipay.order_alipay_user_id
     *
     * @return the value of curriculum_order_alipay.order_alipay_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getOrderAlipayUserId() {
        return orderAlipayUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_order_alipay.order_alipay_user_id
     *
     * @param orderAlipayUserId the value for curriculum_order_alipay.order_alipay_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderAlipayUserId(Long orderAlipayUserId) {
        this.orderAlipayUserId = orderAlipayUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_order_alipay.order_alipay_state
     *
     * @return the value of curriculum_order_alipay.order_alipay_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getOrderAlipayState() {
        return orderAlipayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_order_alipay.order_alipay_state
     *
     * @param orderAlipayState the value for curriculum_order_alipay.order_alipay_state
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderAlipayState(String orderAlipayState) {
        this.orderAlipayState = orderAlipayState == null ? null : orderAlipayState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculum_order_alipay.order_alipay_create_time
     *
     * @return the value of curriculum_order_alipay.order_alipay_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getOrderAlipayCreateTime() {
        return orderAlipayCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculum_order_alipay.order_alipay_create_time
     *
     * @param orderAlipayCreateTime the value for curriculum_order_alipay.order_alipay_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderAlipayCreateTime(Date orderAlipayCreateTime) {
        this.orderAlipayCreateTime = orderAlipayCreateTime;
    }
}