package com.rivis.feng.website.pojo.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DermaBackgroundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public DermaBackgroundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBackgroundIdIsNull() {
            addCriterion("background_id is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdIsNotNull() {
            addCriterion("background_id is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdEqualTo(Long value) {
            addCriterion("background_id =", value, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdNotEqualTo(Long value) {
            addCriterion("background_id <>", value, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdGreaterThan(Long value) {
            addCriterion("background_id >", value, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdGreaterThanOrEqualTo(Long value) {
            addCriterion("background_id >=", value, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdLessThan(Long value) {
            addCriterion("background_id <", value, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdLessThanOrEqualTo(Long value) {
            addCriterion("background_id <=", value, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdIn(List<Long> values) {
            addCriterion("background_id in", values, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdNotIn(List<Long> values) {
            addCriterion("background_id not in", values, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdBetween(Long value1, Long value2) {
            addCriterion("background_id between", value1, value2, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundIdNotBetween(Long value1, Long value2) {
            addCriterion("background_id not between", value1, value2, "backgroundId");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameIsNull() {
            addCriterion("background_name is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameIsNotNull() {
            addCriterion("background_name is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameEqualTo(String value) {
            addCriterion("background_name =", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameNotEqualTo(String value) {
            addCriterion("background_name <>", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameGreaterThan(String value) {
            addCriterion("background_name >", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameGreaterThanOrEqualTo(String value) {
            addCriterion("background_name >=", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameLessThan(String value) {
            addCriterion("background_name <", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameLessThanOrEqualTo(String value) {
            addCriterion("background_name <=", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameLike(String value) {
            addCriterion("background_name like", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameNotLike(String value) {
            addCriterion("background_name not like", value, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameIn(List<String> values) {
            addCriterion("background_name in", values, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameNotIn(List<String> values) {
            addCriterion("background_name not in", values, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameBetween(String value1, String value2) {
            addCriterion("background_name between", value1, value2, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundNameNotBetween(String value1, String value2) {
            addCriterion("background_name not between", value1, value2, "backgroundName");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlIsNull() {
            addCriterion("background_url is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlIsNotNull() {
            addCriterion("background_url is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlEqualTo(String value) {
            addCriterion("background_url =", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlNotEqualTo(String value) {
            addCriterion("background_url <>", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlGreaterThan(String value) {
            addCriterion("background_url >", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlGreaterThanOrEqualTo(String value) {
            addCriterion("background_url >=", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlLessThan(String value) {
            addCriterion("background_url <", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlLessThanOrEqualTo(String value) {
            addCriterion("background_url <=", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlLike(String value) {
            addCriterion("background_url like", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlNotLike(String value) {
            addCriterion("background_url not like", value, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlIn(List<String> values) {
            addCriterion("background_url in", values, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlNotIn(List<String> values) {
            addCriterion("background_url not in", values, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlBetween(String value1, String value2) {
            addCriterion("background_url between", value1, value2, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundUrlNotBetween(String value1, String value2) {
            addCriterion("background_url not between", value1, value2, "backgroundUrl");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeIsNull() {
            addCriterion("background_create_time is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeIsNotNull() {
            addCriterion("background_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeEqualTo(Date value) {
            addCriterion("background_create_time =", value, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeNotEqualTo(Date value) {
            addCriterion("background_create_time <>", value, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeGreaterThan(Date value) {
            addCriterion("background_create_time >", value, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("background_create_time >=", value, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeLessThan(Date value) {
            addCriterion("background_create_time <", value, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("background_create_time <=", value, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeIn(List<Date> values) {
            addCriterion("background_create_time in", values, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeNotIn(List<Date> values) {
            addCriterion("background_create_time not in", values, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeBetween(Date value1, Date value2) {
            addCriterion("background_create_time between", value1, value2, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("background_create_time not between", value1, value2, "backgroundCreateTime");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateIsNull() {
            addCriterion("background_state is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateIsNotNull() {
            addCriterion("background_state is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateEqualTo(String value) {
            addCriterion("background_state =", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateNotEqualTo(String value) {
            addCriterion("background_state <>", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateGreaterThan(String value) {
            addCriterion("background_state >", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateGreaterThanOrEqualTo(String value) {
            addCriterion("background_state >=", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateLessThan(String value) {
            addCriterion("background_state <", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateLessThanOrEqualTo(String value) {
            addCriterion("background_state <=", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateLike(String value) {
            addCriterion("background_state like", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateNotLike(String value) {
            addCriterion("background_state not like", value, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateIn(List<String> values) {
            addCriterion("background_state in", values, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateNotIn(List<String> values) {
            addCriterion("background_state not in", values, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateBetween(String value1, String value2) {
            addCriterion("background_state between", value1, value2, "backgroundState");
            return (Criteria) this;
        }

        public Criteria andBackgroundStateNotBetween(String value1, String value2) {
            addCriterion("background_state not between", value1, value2, "backgroundState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table derma_background
     *
     * @mbggenerated do_not_delete_during_merge Sat May 19 23:25:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table derma_background
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}