package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class DermaBackground {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma_background.background_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Long backgroundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma_background.background_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String backgroundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma_background.background_url
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String backgroundUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma_background.background_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Date backgroundCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma_background.background_state
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String backgroundState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma_background.background_id
     *
     * @return the value of derma_background.background_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Long getBackgroundId() {
        return backgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma_background.background_id
     *
     * @param backgroundId the value for derma_background.background_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setBackgroundId(Long backgroundId) {
        this.backgroundId = backgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma_background.background_name
     *
     * @return the value of derma_background.background_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getBackgroundName() {
        return backgroundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma_background.background_name
     *
     * @param backgroundName the value for derma_background.background_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setBackgroundName(String backgroundName) {
        this.backgroundName = backgroundName == null ? null : backgroundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma_background.background_url
     *
     * @return the value of derma_background.background_url
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getBackgroundUrl() {
        return backgroundUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma_background.background_url
     *
     * @param backgroundUrl the value for derma_background.background_url
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setBackgroundUrl(String backgroundUrl) {
        this.backgroundUrl = backgroundUrl == null ? null : backgroundUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma_background.background_create_time
     *
     * @return the value of derma_background.background_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Date getBackgroundCreateTime() {
        return backgroundCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma_background.background_create_time
     *
     * @param backgroundCreateTime the value for derma_background.background_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setBackgroundCreateTime(Date backgroundCreateTime) {
        this.backgroundCreateTime = backgroundCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma_background.background_state
     *
     * @return the value of derma_background.background_state
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getBackgroundState() {
        return backgroundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma_background.background_state
     *
     * @param backgroundState the value for derma_background.background_state
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setBackgroundState(String backgroundState) {
        this.backgroundState = backgroundState == null ? null : backgroundState.trim();
    }
}