package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class Derma {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long dermaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String dermaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_color
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private String dermaColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_module_style_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long dermaModuleStyleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_background_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long dermaBackgroundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Date dermaCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column derma.derma_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    private Long dermaUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_id
     *
     * @return the value of derma.derma_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getDermaId() {
        return dermaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_id
     *
     * @param dermaId the value for derma.derma_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaId(Long dermaId) {
        this.dermaId = dermaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_name
     *
     * @return the value of derma.derma_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getDermaName() {
        return dermaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_name
     *
     * @param dermaName the value for derma.derma_name
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaName(String dermaName) {
        this.dermaName = dermaName == null ? null : dermaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_color
     *
     * @return the value of derma.derma_color
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getDermaColor() {
        return dermaColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_color
     *
     * @param dermaColor the value for derma.derma_color
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaColor(String dermaColor) {
        this.dermaColor = dermaColor == null ? null : dermaColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_module_style_id
     *
     * @return the value of derma.derma_module_style_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getDermaModuleStyleId() {
        return dermaModuleStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_module_style_id
     *
     * @param dermaModuleStyleId the value for derma.derma_module_style_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaModuleStyleId(Long dermaModuleStyleId) {
        this.dermaModuleStyleId = dermaModuleStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_background_id
     *
     * @return the value of derma.derma_background_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getDermaBackgroundId() {
        return dermaBackgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_background_id
     *
     * @param dermaBackgroundId the value for derma.derma_background_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaBackgroundId(Long dermaBackgroundId) {
        this.dermaBackgroundId = dermaBackgroundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_create_time
     *
     * @return the value of derma.derma_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Date getDermaCreateTime() {
        return dermaCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_create_time
     *
     * @param dermaCreateTime the value for derma.derma_create_time
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaCreateTime(Date dermaCreateTime) {
        this.dermaCreateTime = dermaCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column derma.derma_user_id
     *
     * @return the value of derma.derma_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Long getDermaUserId() {
        return dermaUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column derma.derma_user_id
     *
     * @param dermaUserId the value for derma.derma_user_id
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDermaUserId(Long dermaUserId) {
        this.dermaUserId = dermaUserId;
    }
}