package com.rivis.feng.website.pojo.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DermaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public DermaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDermaIdIsNull() {
            addCriterion("derma_id is null");
            return (Criteria) this;
        }

        public Criteria andDermaIdIsNotNull() {
            addCriterion("derma_id is not null");
            return (Criteria) this;
        }

        public Criteria andDermaIdEqualTo(Long value) {
            addCriterion("derma_id =", value, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdNotEqualTo(Long value) {
            addCriterion("derma_id <>", value, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdGreaterThan(Long value) {
            addCriterion("derma_id >", value, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("derma_id >=", value, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdLessThan(Long value) {
            addCriterion("derma_id <", value, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdLessThanOrEqualTo(Long value) {
            addCriterion("derma_id <=", value, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdIn(List<Long> values) {
            addCriterion("derma_id in", values, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdNotIn(List<Long> values) {
            addCriterion("derma_id not in", values, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdBetween(Long value1, Long value2) {
            addCriterion("derma_id between", value1, value2, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaIdNotBetween(Long value1, Long value2) {
            addCriterion("derma_id not between", value1, value2, "dermaId");
            return (Criteria) this;
        }

        public Criteria andDermaNameIsNull() {
            addCriterion("derma_name is null");
            return (Criteria) this;
        }

        public Criteria andDermaNameIsNotNull() {
            addCriterion("derma_name is not null");
            return (Criteria) this;
        }

        public Criteria andDermaNameEqualTo(String value) {
            addCriterion("derma_name =", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameNotEqualTo(String value) {
            addCriterion("derma_name <>", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameGreaterThan(String value) {
            addCriterion("derma_name >", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameGreaterThanOrEqualTo(String value) {
            addCriterion("derma_name >=", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameLessThan(String value) {
            addCriterion("derma_name <", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameLessThanOrEqualTo(String value) {
            addCriterion("derma_name <=", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameLike(String value) {
            addCriterion("derma_name like", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameNotLike(String value) {
            addCriterion("derma_name not like", value, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameIn(List<String> values) {
            addCriterion("derma_name in", values, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameNotIn(List<String> values) {
            addCriterion("derma_name not in", values, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameBetween(String value1, String value2) {
            addCriterion("derma_name between", value1, value2, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaNameNotBetween(String value1, String value2) {
            addCriterion("derma_name not between", value1, value2, "dermaName");
            return (Criteria) this;
        }

        public Criteria andDermaColorIsNull() {
            addCriterion("derma_color is null");
            return (Criteria) this;
        }

        public Criteria andDermaColorIsNotNull() {
            addCriterion("derma_color is not null");
            return (Criteria) this;
        }

        public Criteria andDermaColorEqualTo(String value) {
            addCriterion("derma_color =", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorNotEqualTo(String value) {
            addCriterion("derma_color <>", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorGreaterThan(String value) {
            addCriterion("derma_color >", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorGreaterThanOrEqualTo(String value) {
            addCriterion("derma_color >=", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorLessThan(String value) {
            addCriterion("derma_color <", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorLessThanOrEqualTo(String value) {
            addCriterion("derma_color <=", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorLike(String value) {
            addCriterion("derma_color like", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorNotLike(String value) {
            addCriterion("derma_color not like", value, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorIn(List<String> values) {
            addCriterion("derma_color in", values, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorNotIn(List<String> values) {
            addCriterion("derma_color not in", values, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorBetween(String value1, String value2) {
            addCriterion("derma_color between", value1, value2, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaColorNotBetween(String value1, String value2) {
            addCriterion("derma_color not between", value1, value2, "dermaColor");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdIsNull() {
            addCriterion("derma_module_style_id is null");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdIsNotNull() {
            addCriterion("derma_module_style_id is not null");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdEqualTo(Long value) {
            addCriterion("derma_module_style_id =", value, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdNotEqualTo(Long value) {
            addCriterion("derma_module_style_id <>", value, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdGreaterThan(Long value) {
            addCriterion("derma_module_style_id >", value, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("derma_module_style_id >=", value, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdLessThan(Long value) {
            addCriterion("derma_module_style_id <", value, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdLessThanOrEqualTo(Long value) {
            addCriterion("derma_module_style_id <=", value, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdIn(List<Long> values) {
            addCriterion("derma_module_style_id in", values, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdNotIn(List<Long> values) {
            addCriterion("derma_module_style_id not in", values, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdBetween(Long value1, Long value2) {
            addCriterion("derma_module_style_id between", value1, value2, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaModuleStyleIdNotBetween(Long value1, Long value2) {
            addCriterion("derma_module_style_id not between", value1, value2, "dermaModuleStyleId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdIsNull() {
            addCriterion("derma_background_id is null");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdIsNotNull() {
            addCriterion("derma_background_id is not null");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdEqualTo(Long value) {
            addCriterion("derma_background_id =", value, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdNotEqualTo(Long value) {
            addCriterion("derma_background_id <>", value, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdGreaterThan(Long value) {
            addCriterion("derma_background_id >", value, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdGreaterThanOrEqualTo(Long value) {
            addCriterion("derma_background_id >=", value, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdLessThan(Long value) {
            addCriterion("derma_background_id <", value, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdLessThanOrEqualTo(Long value) {
            addCriterion("derma_background_id <=", value, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdIn(List<Long> values) {
            addCriterion("derma_background_id in", values, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdNotIn(List<Long> values) {
            addCriterion("derma_background_id not in", values, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdBetween(Long value1, Long value2) {
            addCriterion("derma_background_id between", value1, value2, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaBackgroundIdNotBetween(Long value1, Long value2) {
            addCriterion("derma_background_id not between", value1, value2, "dermaBackgroundId");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeIsNull() {
            addCriterion("derma_create_time is null");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeIsNotNull() {
            addCriterion("derma_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeEqualTo(Date value) {
            addCriterion("derma_create_time =", value, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeNotEqualTo(Date value) {
            addCriterion("derma_create_time <>", value, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeGreaterThan(Date value) {
            addCriterion("derma_create_time >", value, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("derma_create_time >=", value, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeLessThan(Date value) {
            addCriterion("derma_create_time <", value, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("derma_create_time <=", value, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeIn(List<Date> values) {
            addCriterion("derma_create_time in", values, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeNotIn(List<Date> values) {
            addCriterion("derma_create_time not in", values, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeBetween(Date value1, Date value2) {
            addCriterion("derma_create_time between", value1, value2, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("derma_create_time not between", value1, value2, "dermaCreateTime");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdIsNull() {
            addCriterion("derma_user_id is null");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdIsNotNull() {
            addCriterion("derma_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdEqualTo(Long value) {
            addCriterion("derma_user_id =", value, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdNotEqualTo(Long value) {
            addCriterion("derma_user_id <>", value, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdGreaterThan(Long value) {
            addCriterion("derma_user_id >", value, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("derma_user_id >=", value, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdLessThan(Long value) {
            addCriterion("derma_user_id <", value, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdLessThanOrEqualTo(Long value) {
            addCriterion("derma_user_id <=", value, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdIn(List<Long> values) {
            addCriterion("derma_user_id in", values, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdNotIn(List<Long> values) {
            addCriterion("derma_user_id not in", values, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdBetween(Long value1, Long value2) {
            addCriterion("derma_user_id between", value1, value2, "dermaUserId");
            return (Criteria) this;
        }

        public Criteria andDermaUserIdNotBetween(Long value1, Long value2) {
            addCriterion("derma_user_id not between", value1, value2, "dermaUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table derma
     *
     * @mbggenerated do_not_delete_during_merge Sat May 19 23:25:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}