package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Long gradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String gradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_state
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String gradeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.grade_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Date gradeCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_id
     *
     * @return the value of grade.grade_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_id
     *
     * @param gradeId the value for grade.grade_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_name
     *
     * @return the value of grade.grade_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_name
     *
     * @param gradeName the value for grade.grade_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName == null ? null : gradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_state
     *
     * @return the value of grade.grade_state
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getGradeState() {
        return gradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_state
     *
     * @param gradeState the value for grade.grade_state
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setGradeState(String gradeState) {
        this.gradeState = gradeState == null ? null : gradeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.grade_create_time
     *
     * @return the value of grade.grade_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Date getGradeCreateTime() {
        return gradeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.grade_create_time
     *
     * @param gradeCreateTime the value for grade.grade_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setGradeCreateTime(Date gradeCreateTime) {
        this.gradeCreateTime = gradeCreateTime;
    }
}