package com.rivis.feng.website.pojo.po;

import java.util.ArrayList;
import java.util.List;

public class SystemMenuRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public SystemMenuRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSystemMenuRoleIdIsNull() {
            addCriterion("system_menu_role_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdIsNotNull() {
            addCriterion("system_menu_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdEqualTo(Long value) {
            addCriterion("system_menu_role_id =", value, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdNotEqualTo(Long value) {
            addCriterion("system_menu_role_id <>", value, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdGreaterThan(Long value) {
            addCriterion("system_menu_role_id >", value, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("system_menu_role_id >=", value, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdLessThan(Long value) {
            addCriterion("system_menu_role_id <", value, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdLessThanOrEqualTo(Long value) {
            addCriterion("system_menu_role_id <=", value, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdIn(List<Long> values) {
            addCriterion("system_menu_role_id in", values, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdNotIn(List<Long> values) {
            addCriterion("system_menu_role_id not in", values, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdBetween(Long value1, Long value2) {
            addCriterion("system_menu_role_id between", value1, value2, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuRoleIdNotBetween(Long value1, Long value2) {
            addCriterion("system_menu_role_id not between", value1, value2, "systemMenuRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdIsNull() {
            addCriterion("system_menu_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdIsNotNull() {
            addCriterion("system_menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdEqualTo(Long value) {
            addCriterion("system_menu_id =", value, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdNotEqualTo(Long value) {
            addCriterion("system_menu_id <>", value, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdGreaterThan(Long value) {
            addCriterion("system_menu_id >", value, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("system_menu_id >=", value, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdLessThan(Long value) {
            addCriterion("system_menu_id <", value, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdLessThanOrEqualTo(Long value) {
            addCriterion("system_menu_id <=", value, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdIn(List<Long> values) {
            addCriterion("system_menu_id in", values, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdNotIn(List<Long> values) {
            addCriterion("system_menu_id not in", values, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdBetween(Long value1, Long value2) {
            addCriterion("system_menu_id between", value1, value2, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemMenuIdNotBetween(Long value1, Long value2) {
            addCriterion("system_menu_id not between", value1, value2, "systemMenuId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdIsNull() {
            addCriterion("system_role_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdIsNotNull() {
            addCriterion("system_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdEqualTo(Long value) {
            addCriterion("system_role_id =", value, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdNotEqualTo(Long value) {
            addCriterion("system_role_id <>", value, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdGreaterThan(Long value) {
            addCriterion("system_role_id >", value, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("system_role_id >=", value, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdLessThan(Long value) {
            addCriterion("system_role_id <", value, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdLessThanOrEqualTo(Long value) {
            addCriterion("system_role_id <=", value, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdIn(List<Long> values) {
            addCriterion("system_role_id in", values, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdNotIn(List<Long> values) {
            addCriterion("system_role_id not in", values, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdBetween(Long value1, Long value2) {
            addCriterion("system_role_id between", value1, value2, "systemRoleId");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIdNotBetween(Long value1, Long value2) {
            addCriterion("system_role_id not between", value1, value2, "systemRoleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_menu_role
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 03 15:46:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_menu_role
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}