package com.rivis.feng.website.pojo.po;

public class SystemViewMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_url
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_path
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private String menuPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_component
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private String menuComponent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_name
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_icon_cls
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private String menuIconCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_keep_alive
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Integer menuKeepAlive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_require_auth
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Integer menuRequireAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_view_menu.menu_parent_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Long menuParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_id
     *
     * @return the value of system_view_menu.menu_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_id
     *
     * @param menuId the value for system_view_menu.menu_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_url
     *
     * @return the value of system_view_menu.menu_url
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_url
     *
     * @param menuUrl the value for system_view_menu.menu_url
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_path
     *
     * @return the value of system_view_menu.menu_path
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_path
     *
     * @param menuPath the value for system_view_menu.menu_path
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath == null ? null : menuPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_component
     *
     * @return the value of system_view_menu.menu_component
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getMenuComponent() {
        return menuComponent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_component
     *
     * @param menuComponent the value for system_view_menu.menu_component
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuComponent(String menuComponent) {
        this.menuComponent = menuComponent == null ? null : menuComponent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_name
     *
     * @return the value of system_view_menu.menu_name
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_name
     *
     * @param menuName the value for system_view_menu.menu_name
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_icon_cls
     *
     * @return the value of system_view_menu.menu_icon_cls
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getMenuIconCls() {
        return menuIconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_icon_cls
     *
     * @param menuIconCls the value for system_view_menu.menu_icon_cls
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuIconCls(String menuIconCls) {
        this.menuIconCls = menuIconCls == null ? null : menuIconCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_keep_alive
     *
     * @return the value of system_view_menu.menu_keep_alive
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Integer getMenuKeepAlive() {
        return menuKeepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_keep_alive
     *
     * @param menuKeepAlive the value for system_view_menu.menu_keep_alive
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuKeepAlive(Integer menuKeepAlive) {
        this.menuKeepAlive = menuKeepAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_require_auth
     *
     * @return the value of system_view_menu.menu_require_auth
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Integer getMenuRequireAuth() {
        return menuRequireAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_require_auth
     *
     * @param menuRequireAuth the value for system_view_menu.menu_require_auth
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuRequireAuth(Integer menuRequireAuth) {
        this.menuRequireAuth = menuRequireAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_view_menu.menu_parent_id
     *
     * @return the value of system_view_menu.menu_parent_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Long getMenuParentId() {
        return menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_view_menu.menu_parent_id
     *
     * @param menuParentId the value for system_view_menu.menu_parent_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setMenuParentId(Long menuParentId) {
        this.menuParentId = menuParentId;
    }
}