package com.rivis.feng.website.pojo.po;

import java.util.ArrayList;
import java.util.List;

public class SystemViewMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public SystemViewMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("menu_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("menu_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Long value) {
            addCriterion("menu_id =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Long value) {
            addCriterion("menu_id <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Long value) {
            addCriterion("menu_id >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("menu_id >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Long value) {
            addCriterion("menu_id <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Long value) {
            addCriterion("menu_id <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Long> values) {
            addCriterion("menu_id in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Long> values) {
            addCriterion("menu_id not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Long value1, Long value2) {
            addCriterion("menu_id between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Long value1, Long value2) {
            addCriterion("menu_id not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIsNull() {
            addCriterion("menu_url is null");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIsNotNull() {
            addCriterion("menu_url is not null");
            return (Criteria) this;
        }

        public Criteria andMenuUrlEqualTo(String value) {
            addCriterion("menu_url =", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotEqualTo(String value) {
            addCriterion("menu_url <>", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlGreaterThan(String value) {
            addCriterion("menu_url >", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlGreaterThanOrEqualTo(String value) {
            addCriterion("menu_url >=", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLessThan(String value) {
            addCriterion("menu_url <", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLessThanOrEqualTo(String value) {
            addCriterion("menu_url <=", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlLike(String value) {
            addCriterion("menu_url like", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotLike(String value) {
            addCriterion("menu_url not like", value, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlIn(List<String> values) {
            addCriterion("menu_url in", values, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotIn(List<String> values) {
            addCriterion("menu_url not in", values, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlBetween(String value1, String value2) {
            addCriterion("menu_url between", value1, value2, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuUrlNotBetween(String value1, String value2) {
            addCriterion("menu_url not between", value1, value2, "menuUrl");
            return (Criteria) this;
        }

        public Criteria andMenuPathIsNull() {
            addCriterion("menu_path is null");
            return (Criteria) this;
        }

        public Criteria andMenuPathIsNotNull() {
            addCriterion("menu_path is not null");
            return (Criteria) this;
        }

        public Criteria andMenuPathEqualTo(String value) {
            addCriterion("menu_path =", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathNotEqualTo(String value) {
            addCriterion("menu_path <>", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathGreaterThan(String value) {
            addCriterion("menu_path >", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathGreaterThanOrEqualTo(String value) {
            addCriterion("menu_path >=", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathLessThan(String value) {
            addCriterion("menu_path <", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathLessThanOrEqualTo(String value) {
            addCriterion("menu_path <=", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathLike(String value) {
            addCriterion("menu_path like", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathNotLike(String value) {
            addCriterion("menu_path not like", value, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathIn(List<String> values) {
            addCriterion("menu_path in", values, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathNotIn(List<String> values) {
            addCriterion("menu_path not in", values, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathBetween(String value1, String value2) {
            addCriterion("menu_path between", value1, value2, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuPathNotBetween(String value1, String value2) {
            addCriterion("menu_path not between", value1, value2, "menuPath");
            return (Criteria) this;
        }

        public Criteria andMenuComponentIsNull() {
            addCriterion("menu_component is null");
            return (Criteria) this;
        }

        public Criteria andMenuComponentIsNotNull() {
            addCriterion("menu_component is not null");
            return (Criteria) this;
        }

        public Criteria andMenuComponentEqualTo(String value) {
            addCriterion("menu_component =", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentNotEqualTo(String value) {
            addCriterion("menu_component <>", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentGreaterThan(String value) {
            addCriterion("menu_component >", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentGreaterThanOrEqualTo(String value) {
            addCriterion("menu_component >=", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentLessThan(String value) {
            addCriterion("menu_component <", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentLessThanOrEqualTo(String value) {
            addCriterion("menu_component <=", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentLike(String value) {
            addCriterion("menu_component like", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentNotLike(String value) {
            addCriterion("menu_component not like", value, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentIn(List<String> values) {
            addCriterion("menu_component in", values, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentNotIn(List<String> values) {
            addCriterion("menu_component not in", values, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentBetween(String value1, String value2) {
            addCriterion("menu_component between", value1, value2, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuComponentNotBetween(String value1, String value2) {
            addCriterion("menu_component not between", value1, value2, "menuComponent");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("menu_name is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("menu_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("menu_name =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("menu_name <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("menu_name >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("menu_name >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("menu_name <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("menu_name <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("menu_name like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("menu_name not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("menu_name in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("menu_name not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("menu_name between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("menu_name not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsIsNull() {
            addCriterion("menu_icon_cls is null");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsIsNotNull() {
            addCriterion("menu_icon_cls is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsEqualTo(String value) {
            addCriterion("menu_icon_cls =", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsNotEqualTo(String value) {
            addCriterion("menu_icon_cls <>", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsGreaterThan(String value) {
            addCriterion("menu_icon_cls >", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsGreaterThanOrEqualTo(String value) {
            addCriterion("menu_icon_cls >=", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsLessThan(String value) {
            addCriterion("menu_icon_cls <", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsLessThanOrEqualTo(String value) {
            addCriterion("menu_icon_cls <=", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsLike(String value) {
            addCriterion("menu_icon_cls like", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsNotLike(String value) {
            addCriterion("menu_icon_cls not like", value, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsIn(List<String> values) {
            addCriterion("menu_icon_cls in", values, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsNotIn(List<String> values) {
            addCriterion("menu_icon_cls not in", values, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsBetween(String value1, String value2) {
            addCriterion("menu_icon_cls between", value1, value2, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuIconClsNotBetween(String value1, String value2) {
            addCriterion("menu_icon_cls not between", value1, value2, "menuIconCls");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveIsNull() {
            addCriterion("menu_keep_alive is null");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveIsNotNull() {
            addCriterion("menu_keep_alive is not null");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveEqualTo(Integer value) {
            addCriterion("menu_keep_alive =", value, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveNotEqualTo(Integer value) {
            addCriterion("menu_keep_alive <>", value, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveGreaterThan(Integer value) {
            addCriterion("menu_keep_alive >", value, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_keep_alive >=", value, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveLessThan(Integer value) {
            addCriterion("menu_keep_alive <", value, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveLessThanOrEqualTo(Integer value) {
            addCriterion("menu_keep_alive <=", value, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveIn(List<Integer> values) {
            addCriterion("menu_keep_alive in", values, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveNotIn(List<Integer> values) {
            addCriterion("menu_keep_alive not in", values, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveBetween(Integer value1, Integer value2) {
            addCriterion("menu_keep_alive between", value1, value2, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuKeepAliveNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_keep_alive not between", value1, value2, "menuKeepAlive");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthIsNull() {
            addCriterion("menu_require_auth is null");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthIsNotNull() {
            addCriterion("menu_require_auth is not null");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthEqualTo(Integer value) {
            addCriterion("menu_require_auth =", value, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthNotEqualTo(Integer value) {
            addCriterion("menu_require_auth <>", value, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthGreaterThan(Integer value) {
            addCriterion("menu_require_auth >", value, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthGreaterThanOrEqualTo(Integer value) {
            addCriterion("menu_require_auth >=", value, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthLessThan(Integer value) {
            addCriterion("menu_require_auth <", value, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthLessThanOrEqualTo(Integer value) {
            addCriterion("menu_require_auth <=", value, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthIn(List<Integer> values) {
            addCriterion("menu_require_auth in", values, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthNotIn(List<Integer> values) {
            addCriterion("menu_require_auth not in", values, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthBetween(Integer value1, Integer value2) {
            addCriterion("menu_require_auth between", value1, value2, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuRequireAuthNotBetween(Integer value1, Integer value2) {
            addCriterion("menu_require_auth not between", value1, value2, "menuRequireAuth");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdIsNull() {
            addCriterion("menu_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdIsNotNull() {
            addCriterion("menu_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdEqualTo(Long value) {
            addCriterion("menu_parent_id =", value, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdNotEqualTo(Long value) {
            addCriterion("menu_parent_id <>", value, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdGreaterThan(Long value) {
            addCriterion("menu_parent_id >", value, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("menu_parent_id >=", value, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdLessThan(Long value) {
            addCriterion("menu_parent_id <", value, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdLessThanOrEqualTo(Long value) {
            addCriterion("menu_parent_id <=", value, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdIn(List<Long> values) {
            addCriterion("menu_parent_id in", values, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdNotIn(List<Long> values) {
            addCriterion("menu_parent_id not in", values, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdBetween(Long value1, Long value2) {
            addCriterion("menu_parent_id between", value1, value2, "menuParentId");
            return (Criteria) this;
        }

        public Criteria andMenuParentIdNotBetween(Long value1, Long value2) {
            addCriterion("menu_parent_id not between", value1, value2, "menuParentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_view_menu
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 03 15:46:16 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}