package com.rivis.feng.website.pojo.po;

public class SystemMenuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_role.system_menu_role_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Long systemMenuRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_role.system_menu_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Long systemMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_menu_role.system_role_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    private Long systemRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_role.system_menu_role_id
     *
     * @return the value of system_menu_role.system_menu_role_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Long getSystemMenuRoleId() {
        return systemMenuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_role.system_menu_role_id
     *
     * @param systemMenuRoleId the value for system_menu_role.system_menu_role_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setSystemMenuRoleId(Long systemMenuRoleId) {
        this.systemMenuRoleId = systemMenuRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_role.system_menu_id
     *
     * @return the value of system_menu_role.system_menu_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Long getSystemMenuId() {
        return systemMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_role.system_menu_id
     *
     * @param systemMenuId the value for system_menu_role.system_menu_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setSystemMenuId(Long systemMenuId) {
        this.systemMenuId = systemMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_menu_role.system_role_id
     *
     * @return the value of system_menu_role.system_role_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public Long getSystemRoleId() {
        return systemRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_menu_role.system_role_id
     *
     * @param systemRoleId the value for system_menu_role.system_role_id
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    public void setSystemRoleId(Long systemRoleId) {
        this.systemRoleId = systemRoleId;
    }
}