package com.rivis.feng.website.pojo.po;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.thymeleaf.expression.Lists;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

public class User implements UserDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_picture
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_birthday
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_gender
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_phone
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_city_id
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private Long userCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_address
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_is_delete
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userIsDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_is_vip
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userIsVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_mail
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_create_time
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private Date userCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_from
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    private String userFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_picture
     *
     * @return the value of user.user_picture
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserPicture() {
        return userPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_picture
     *
     * @param userPicture the value for user.user_picture
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserPicture(String userPicture) {
        this.userPicture = userPicture == null ? null : userPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_birthday
     *
     * @return the value of user.user_birthday
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_birthday
     *
     * @param userBirthday the value for user.user_birthday
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_gender
     *
     * @return the value of user.user_gender
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_gender
     *
     * @param userGender the value for user.user_gender
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param userPhone the value for user.user_phone
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_city_id
     *
     * @return the value of user.user_city_id
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public Long getUserCityId() {
        return userCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_city_id
     *
     * @param userCityId the value for user.user_city_id
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserCityId(Long userCityId) {
        this.userCityId = userCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_address
     *
     * @return the value of user.user_address
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_address
     *
     * @param userAddress the value for user.user_address
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_is_delete
     *
     * @return the value of user.user_is_delete
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserIsDelete() {
        return userIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_is_delete
     *
     * @param userIsDelete the value for user.user_is_delete
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserIsDelete(String userIsDelete) {
        this.userIsDelete = userIsDelete == null ? null : userIsDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_is_vip
     *
     * @return the value of user.user_is_vip
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserIsVip() {
        return userIsVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_is_vip
     *
     * @param userIsVip the value for user.user_is_vip
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserIsVip(String userIsVip) {
        this.userIsVip = userIsVip == null ? null : userIsVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_mail
     *
     * @return the value of user.user_mail
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_mail
     *
     * @param userMail the value for user.user_mail
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_create_time
     *
     * @return the value of user.user_create_time
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_create_time
     *
     * @param userCreateTime the value for user.user_create_time
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_from
     *
     * @return the value of user.user_from
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public String getUserFrom() {
        return userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_from
     *
     * @param userFrom the value for user.user_from
     *
     * @mbggenerated Mon May 21 22:23:43 CST 2018
     */
    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom == null ? null : userFrom.trim();
    }

    private List<SystemRole> systemRoles;

    public List<SystemRole> getSystemRoles() {
        return systemRoles;
    }

    public void setSystemRoles(List<SystemRole> systemRoles) {
        this.systemRoles = systemRoles;
    }

    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userPicture='" + userPicture + '\'' +
                ", userBirthday=" + userBirthday +
                ", userGender='" + userGender + '\'' +
                ", userPhone='" + userPhone + '\'' +
                ", userCityId=" + userCityId +
                ", userAddress='" + userAddress + '\'' +
                ", userIsDelete='" + userIsDelete + '\'' +
                ", userIsVip='" + userIsVip + '\'' +
                ", userMail='" + userMail + '\'' +
                ", userCreateTime=" + userCreateTime +
                ", userFrom='" + userFrom + '\'' +
                ", systemRoles=" + systemRoles +
                '}';
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<GrantedAuthority> authorities = new ArrayList<>();
        for (SystemRole systemRole : systemRoles) {
            authorities.add(new SimpleGrantedAuthority(systemRole.getRoleName()));
        }
        return authorities;

    }

    @Override
    public String getPassword() {
        return getUserPassword();
    }

    @Override
    public String getUsername() {
        return getUserPhone();
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}