package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class UserStateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_type
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Date logCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_ip
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String logIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_area
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String logArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_equipment
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String logEquipment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_state_log.log_soft
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String logSoft;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_id
     *
     * @return the value of user_state_log.log_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_id
     *
     * @param logId the value for user_state_log.log_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_type
     *
     * @return the value of user_state_log.log_type
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_type
     *
     * @param logType the value for user_state_log.log_type
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_create_time
     *
     * @return the value of user_state_log.log_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Date getLogCreateTime() {
        return logCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_create_time
     *
     * @param logCreateTime the value for user_state_log.log_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogCreateTime(Date logCreateTime) {
        this.logCreateTime = logCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_ip
     *
     * @return the value of user_state_log.log_ip
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getLogIp() {
        return logIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_ip
     *
     * @param logIp the value for user_state_log.log_ip
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogIp(String logIp) {
        this.logIp = logIp == null ? null : logIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_area
     *
     * @return the value of user_state_log.log_area
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getLogArea() {
        return logArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_area
     *
     * @param logArea the value for user_state_log.log_area
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogArea(String logArea) {
        this.logArea = logArea == null ? null : logArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_equipment
     *
     * @return the value of user_state_log.log_equipment
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getLogEquipment() {
        return logEquipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_equipment
     *
     * @param logEquipment the value for user_state_log.log_equipment
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogEquipment(String logEquipment) {
        this.logEquipment = logEquipment == null ? null : logEquipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_state_log.log_soft
     *
     * @return the value of user_state_log.log_soft
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getLogSoft() {
        return logSoft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_state_log.log_soft
     *
     * @param logSoft the value for user_state_log.log_soft
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setLogSoft(String logSoft) {
        this.logSoft = logSoft == null ? null : logSoft.trim();
    }
}