package com.rivis.feng.website.pojo.po;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pricture
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_birthday
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_gender
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_phone
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_city_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Long userCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_address
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_is_delete
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userIsDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_is_vip
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userIsVip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_mail
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private Date userCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_from
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    private String userFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pricture
     *
     * @return the value of user.user_pricture
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserPicture() {
        return userPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pricture
     *
     * @param userPicture the value for user.user_pricture
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserPicture(String userPicture) {
        this.userPicture = userPicture == null ? null : userPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_birthday
     *
     * @return the value of user.user_birthday
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_birthday
     *
     * @param userBirthday the value for user.user_birthday
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_gender
     *
     * @return the value of user.user_gender
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_gender
     *
     * @param userGender the value for user.user_gender
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param userPhone the value for user.user_phone
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_city_id
     *
     * @return the value of user.user_city_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Long getUserCityId() {
        return userCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_city_id
     *
     * @param userCityId the value for user.user_city_id
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserCityId(Long userCityId) {
        this.userCityId = userCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_address
     *
     * @return the value of user.user_address
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_address
     *
     * @param userAddress the value for user.user_address
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_is_delete
     *
     * @return the value of user.user_is_delete
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserIsDelete() {
        return userIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_is_delete
     *
     * @param userIsDelete the value for user.user_is_delete
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserIsDelete(String userIsDelete) {
        this.userIsDelete = userIsDelete == null ? null : userIsDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_is_vip
     *
     * @return the value of user.user_is_vip
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserIsVip() {
        return userIsVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_is_vip
     *
     * @param userIsVip the value for user.user_is_vip
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserIsVip(String userIsVip) {
        this.userIsVip = userIsVip == null ? null : userIsVip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_mail
     *
     * @return the value of user.user_mail
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_mail
     *
     * @param userMail the value for user.user_mail
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_create_time
     *
     * @return the value of user.user_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_create_time
     *
     * @param userCreateTime the value for user.user_create_time
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_from
     *
     * @return the value of user.user_from
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public String getUserFrom() {
        return userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_from
     *
     * @param userFrom the value for user.user_from
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom == null ? null : userFrom.trim();
    }
}