package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.Advertising;
import com.rivis.feng.website.pojo.po.AdvertisingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AdvertisingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long advertisingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<Advertising> selectByExample(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    Advertising selectByPrimaryKey(Long advertisingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Advertising record, @Param("example") AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") Advertising record, @Param("example") AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(Advertising record);
}