package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumOutline;
import com.rivis.feng.website.pojo.po.CurriculumOutlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CurriculumOutlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumOutlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumOutlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long outlineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumOutline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumOutline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumOutline> selectByExample(CurriculumOutlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumOutline selectByPrimaryKey(Long outlineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumOutline record, @Param("example") CurriculumOutlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumOutline record, @Param("example") CurriculumOutlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumOutline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_outline
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumOutline record);
}