package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumAppraise;
import com.rivis.feng.website.pojo.po.CurriculumAppraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurriculumAppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long appraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumAppraise> selectByExample(CurriculumAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumAppraise selectByPrimaryKey(Long appraiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumAppraise record, @Param("example") CurriculumAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumAppraise record, @Param("example") CurriculumAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumAppraise record);
}