package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumOrderWechat;
import com.rivis.feng.website.pojo.po.CurriculumOrderWechatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CurriculumOrderWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long orderWechatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumOrderWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumOrderWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumOrderWechat> selectByExample(CurriculumOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumOrderWechat selectByPrimaryKey(Long orderWechatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumOrderWechat record, @Param("example") CurriculumOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumOrderWechat record, @Param("example") CurriculumOrderWechatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumOrderWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_wechat
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumOrderWechat record);
}