package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumFeature;
import com.rivis.feng.website.pojo.po.CurriculumFeatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurriculumFeatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long featureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumFeature> selectByExample(CurriculumFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumFeature selectByPrimaryKey(Long featureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumFeature record, @Param("example") CurriculumFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumFeature record, @Param("example") CurriculumFeatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumFeature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_feature
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumFeature record);
}