package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumAppraiseReply;
import com.rivis.feng.website.pojo.po.CurriculumAppraiseReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurriculumAppraiseReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumAppraiseReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumAppraiseReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumAppraiseReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumAppraiseReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumAppraiseReply> selectByExample(CurriculumAppraiseReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumAppraiseReply selectByPrimaryKey(Long replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumAppraiseReply record, @Param("example") CurriculumAppraiseReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumAppraiseReply record, @Param("example") CurriculumAppraiseReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumAppraiseReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_appraise_reply
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumAppraiseReply record);
}