package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumVideo;
import com.rivis.feng.website.pojo.po.CurriculumVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurriculumVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumVideo> selectByExample(CurriculumVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumVideo selectByPrimaryKey(Long videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumVideo record, @Param("example") CurriculumVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumVideo record, @Param("example") CurriculumVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_video
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumVideo record);
}