package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.CurriculumOrderAlipay;
import com.rivis.feng.website.pojo.po.CurriculumOrderAlipayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CurriculumOrderAlipayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long orderAlipayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(CurriculumOrderAlipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(CurriculumOrderAlipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<CurriculumOrderAlipay> selectByExample(CurriculumOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    CurriculumOrderAlipay selectByPrimaryKey(Long orderAlipayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurriculumOrderAlipay record, @Param("example") CurriculumOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") CurriculumOrderAlipay record, @Param("example") CurriculumOrderAlipayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(CurriculumOrderAlipay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum_order_alipay
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(CurriculumOrderAlipay record);
}