package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.Curriculum;
import com.rivis.feng.website.pojo.po.CurriculumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurriculumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(CurriculumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(CurriculumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long curriculumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(Curriculum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(Curriculum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<Curriculum> selectByExample(CurriculumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    Curriculum selectByPrimaryKey(Long curriculumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Curriculum record, @Param("example") CurriculumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") Curriculum record, @Param("example") CurriculumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(Curriculum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculum
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(Curriculum record);
}