package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.Derma;
import com.rivis.feng.website.pojo.po.DermaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface DermaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int countByExample(DermaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByExample(DermaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int deleteByPrimaryKey(Long dermaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insert(Derma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int insertSelective(Derma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    List<Derma> selectByExample(DermaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    Derma selectByPrimaryKey(Long dermaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Derma record, @Param("example") DermaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByExample(@Param("record") Derma record, @Param("example") DermaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKeySelective(Derma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table derma
     *
     * @mbggenerated Sat May 19 23:25:22 CST 2018
     */
    int updateByPrimaryKey(Derma record);
}