package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.SystemSetting;
import com.rivis.feng.website.pojo.po.SystemSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int countByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int deleteByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int deleteByPrimaryKey(Long settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int insert(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int insertSelective(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    List<SystemSetting> selectByExample(SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    SystemSetting selectByPrimaryKey(Long settingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByExample(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByPrimaryKeySelective(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_setting
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByPrimaryKey(SystemSetting record);
}