package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.SystemViewMenu;
import com.rivis.feng.website.pojo.po.SystemViewMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemViewMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int countByExample(SystemViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int deleteByExample(SystemViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int insert(SystemViewMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int insertSelective(SystemViewMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    List<SystemViewMenu> selectByExample(SystemViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    SystemViewMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") SystemViewMenu record, @Param("example") SystemViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int updateByExample(@Param("record") SystemViewMenu record, @Param("example") SystemViewMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int updateByPrimaryKeySelective(SystemViewMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_view_menu
     *
     * @mbggenerated Sun Jun 03 15:46:16 CST 2018
     */
    int updateByPrimaryKey(SystemViewMenu record);
}