package com.rivis.feng.website.dao;

import com.rivis.feng.website.pojo.po.UserStateLog;
import com.rivis.feng.website.pojo.po.UserStateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserStateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int countByExample(UserStateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int deleteByExample(UserStateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int insert(UserStateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int insertSelective(UserStateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    List<UserStateLog> selectByExample(UserStateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    UserStateLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserStateLog record, @Param("example") UserStateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByExample(@Param("record") UserStateLog record, @Param("example") UserStateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByPrimaryKeySelective(UserStateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_state_log
     *
     * @mbggenerated Sat May 19 23:25:23 CST 2018
     */
    int updateByPrimaryKey(UserStateLog record);
}