spring:
  datasource:
    driver-class-name: 'com.mysql.jdbc.Driver'
    url: 'jdbc:mysql://127.0.0.1:3306/officialwebsite?useSSL=false'
    username: 'root'
    password: 'RivisFeng0310'
mybatis:
  mapper-locations: 'classpath:mapper/*Mapper.xml'
hello: hello world
